name: pill-request-auto-merge

on:
  pull_request:

permissions:
  id-token: write
  contents: write
  pull-requests: write
  checks: write

jobs:
  pull-request-auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v4

      - name: Enable auto-merge for Pull Request
        run: |
          gh pr review --approve "$PR_URL"
          gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
